import { create } from "zustand";
import {
  Python,
  Java,
  Javascript,
  Cplusplus,
  Csharp,
  Dart,
  Php,
  Html5,
  Css3,
  React,
  TailwindCss,
  Flutter,
  Expressdotjs,
  Nodedotjs,
  Discord,
  Vite,
  Postman,
  Git,
  Github,
  Postgresql,
  Mysql,
  Prisma,
  Neon,
  Firebase,
  Arduino,
  Sfml,
  Render,
  Replit,
} from "@thesvg/react";

export const useStack = create(() => ({
  stacks: [
    { title: "Python", icon: Python },
    { title: "Java", icon: Java },
    { title: "Javascript", icon: Javascript },
    { title: "C++", icon: Cplusplus },
    { title: "C#", icon: Csharp },
    { title: "Dart", icon: Dart },
    { title: "PHP", icon: Php },
    { title: "HTML5", icon: Html5 },
    { title: "CSS3", icon: Css3 },
    { title: "React", icon: React },
    { title: "Tailwind", icon: TailwindCss },
    { title: "Flutter", icon: Flutter },
    { title: "Express.js", icon: Expressdotjs },
    { title: "Node.js", icon: Nodedotjs },
    { title: "Discord.py", icon: Discord },
    { title: "Vite", icon: Vite },
    { title: "Postman", icon: Postman },
    { title: "Git", icon: Git },
    { title: "Github", icon: Github },
    { title: "PostgreSQL", icon: Postgresql },
    { title: "MySQL", icon: Mysql },
    { title: "Prisma", icon: Prisma },
    { title: "Neon", icon: Neon },
    { title: "Firebase", icon: Firebase },
    { title: "Arduino", icon: Arduino },
    { title: "SFML", icon: Sfml },
    { title: "Render", icon: Render },
    { title: "Replit", icon: Replit },
  ],
}));
